import { loadEnv } from "../config/env.js";
import { createSupabaseServiceClient } from "../shared/supabase/client.js";
import { assertSupabaseOk } from "../shared/supabase/result.js";

const env = loadEnv();
const supabase = createSupabaseServiceClient(env);
const tenantId = "graphflow-main";
const now = new Date();

function iso(daysFromNow = 0) {
  const date = new Date(now);
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString();
}

function money(value: number) {
  return Number(value.toFixed(2));
}

async function upsertRows(table: string, rows: Array<Record<string, unknown>>, label: string) {
  if (!rows.length) return 0;

  const result = await supabase
    .from(table)
    .upsert(rows, { onConflict: "id" })
    .select("id");

  assertSupabaseOk(result.error, label);
  return result.data?.length ?? 0;
}

const fiscal = {
  ncm: "49111090",
  cest: "",
  origin: "0",
  cfop: "5102",
  icmsCstCsosn: "102",
  pisCst: "01",
  cofinsCst: "01",
  ipiCst: "",
  icmsRate: "18",
  pisRate: "1.65",
  cofinsRate: "7.6",
  ipiRate: "",
  additionalInfo: "Material grafico personalizado.",
};

const products = [
  {
    id: "demo-prd-cartao-premium",
    sectorId: "sec-impressao",
    sectorName: "Impressao",
    sku: "GF-CV-PREM-300",
    name: "Cartao de Visita Premium 300g",
    category: "Cartoes de Visita",
    description: "Cartao 9x5cm em couche 300g, laminação fosca e verniz localizado.",
    thumbnailUrl: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=900&q=80",
    priceCost: 34.9,
    priceSale: 89.9,
    unitType: "UN",
    stockQty: 18000,
    stockMin: 2500,
    stockMax: 40000,
    trackStock: true,
    allowFractional: true,
    minOrderQty: 500,
    minFractionQty: 100,
    tags: ["cartao", "premium", "verniz"],
    isActive: true,
    isFeatured: true,
    attributes: {
      leadTime: "3 dias",
      commercialDescription: "Cartao de visita premium 300g",
      gtin: "SEM GTIN",
      availableColors: ["4x0", "4x4"],
      stockUnit: "UN",
      commercialUnit: "UN",
      fiscal,
    },
  },
  {
    id: "demo-prd-folder-promocional",
    sectorId: "sec-impressao",
    sectorName: "Impressao",
    sku: "GF-FOLDER-A4-150",
    name: "Folder Promocional A4 150g",
    category: "Folders",
    description: "Folder A4 4x4 cores em couche 150g com dobra central.",
    thumbnailUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    priceCost: 72,
    priceSale: 189.9,
    unitType: "UN",
    stockQty: 9600,
    stockMin: 1600,
    stockMax: 26000,
    trackStock: true,
    allowFractional: true,
    minOrderQty: 500,
    minFractionQty: 250,
    tags: ["folder", "promocional", "a4"],
    isActive: true,
    isFeatured: true,
    attributes: {
      leadTime: "4 dias",
      commercialDescription: "Folder promocional A4 150g",
      gtin: "SEM GTIN",
      availableColors: ["4x4"],
      stockUnit: "UN",
      commercialUnit: "UN",
      fiscal,
    },
  },
  {
    id: "demo-prd-banner-lona",
    sectorId: "sec-acabamento",
    sectorName: "Acabamento",
    sku: "GF-BAN-LONA-440",
    name: "Banner Lona 440g com Bastao",
    category: "Banners",
    description: "Banner em lona 440g com bastao, ponteira e cordao.",
    thumbnailUrl: "https://images.unsplash.com/photo-1516387938699-a93567ec168e?auto=format&fit=crop&w=900&q=80",
    priceCost: 38,
    priceSale: 99.9,
    unitType: "UN",
    stockQty: 410,
    stockMin: 60,
    stockMax: 1200,
    trackStock: true,
    allowFractional: false,
    minOrderQty: 1,
    minFractionQty: 1,
    tags: ["banner", "lona", "evento"],
    isActive: true,
    isFeatured: true,
    attributes: {
      leadTime: "2 dias",
      commercialDescription: "Banner lona 440g com bastao",
      gtin: "SEM GTIN",
      stockUnit: "UN",
      commercialUnit: "UN",
      fiscal,
    },
  },
  {
    id: "demo-prd-adesivo-vinil",
    sectorId: "sec-arte-final",
    sectorName: "Arte Final",
    sku: "GF-ADES-VINIL-5",
    name: "Adesivo Vinil Redondo 5cm",
    category: "Adesivos",
    description: "Adesivo redondo em vinil branco, corte especial e impressao colorida.",
    thumbnailUrl: "https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?auto=format&fit=crop&w=900&q=80",
    priceCost: 24,
    priceSale: 69.9,
    unitType: "UN",
    stockQty: 14500,
    stockMin: 2200,
    stockMax: 40000,
    trackStock: true,
    allowFractional: true,
    minOrderQty: 250,
    minFractionQty: 50,
    tags: ["adesivo", "vinil", "corte"],
    isActive: true,
    isFeatured: false,
    attributes: {
      leadTime: "2 dias",
      commercialDescription: "Adesivo vinil redondo 5cm",
      gtin: "SEM GTIN",
      availableColors: ["branco", "transparente"],
      stockUnit: "UN",
      commercialUnit: "UN",
      fiscal,
    },
  },
  {
    id: "demo-prd-cardapio-laminado",
    sectorId: "sec-acabamento",
    sectorName: "Acabamento",
    sku: "GF-CARD-LAM-A3",
    name: "Cardapio Laminado A3",
    category: "Cardapios",
    description: "Cardapio A3 plastificado, ideal para restaurantes e cafeterias.",
    thumbnailUrl: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=80",
    priceCost: 8.9,
    priceSale: 24.9,
    unitType: "UN",
    stockQty: 720,
    stockMin: 100,
    stockMax: 2500,
    trackStock: true,
    allowFractional: false,
    minOrderQty: 10,
    minFractionQty: 1,
    tags: ["cardapio", "laminado", "restaurante"],
    isActive: true,
    isFeatured: false,
    attributes: {
      leadTime: "5 dias",
      commercialDescription: "Cardapio laminado A3",
      gtin: "SEM GTIN",
      stockUnit: "UN",
      commercialUnit: "UN",
      fiscal,
    },
  },
  {
    id: "demo-prd-caixa-kraft",
    sectorId: "demo-sec-expedicao",
    sectorName: "Expedicao",
    sku: "GF-CAIXA-KRAFT-18",
    name: "Caixa Kraft Personalizada 18x18x10",
    category: "Embalagens",
    description: "Caixa kraft personalizada para presentes, delivery e kits corporativos.",
    thumbnailUrl: "https://images.unsplash.com/photo-1607344645866-009c320f0ab8?auto=format&fit=crop&w=900&q=80",
    priceCost: 4.4,
    priceSale: 12.9,
    unitType: "UN",
    stockQty: 1500,
    stockMin: 300,
    stockMax: 5000,
    trackStock: true,
    allowFractional: false,
    minOrderQty: 50,
    minFractionQty: 1,
    tags: ["caixa", "kraft", "embalagem"],
    isActive: true,
    isFeatured: true,
    attributes: {
      leadTime: "7 dias",
      commercialDescription: "Caixa kraft personalizada 18x18x10",
      gtin: "SEM GTIN",
      stockUnit: "UN",
      commercialUnit: "UN",
      fiscal,
    },
  },
];

const orderItems = [
  {
    id: "demo-itm-3001-cartao",
    orderId: "demo-ord-3001",
    productId: "demo-prd-cartao-premium",
    description: "Cartao de Visita Premium 300g",
    quantity: 1000,
    unitPrice: 0.22,
    discount: 0,
    total: 220,
    status: "IN_PROGRESS",
    position: 0,
    priority: "HIGH",
    dueDate: iso(4),
    assignedUserId: "demo-usr-producao",
    sectorId: "sec-impressao",
    machineId: "demo-maq-indigo",
    startedAt: iso(-1),
    metadata: { observacao: "Frente e verso, verniz localizado" },
  },
  {
    id: "demo-itm-3001-folder",
    orderId: "demo-ord-3001",
    productId: "demo-prd-folder-promocional",
    description: "Folder Promocional A4 150g",
    quantity: 500,
    unitPrice: 0.38,
    discount: 0,
    total: 190,
    status: "QUEUED",
    position: 1,
    priority: "NORMAL",
    dueDate: iso(5),
    assignedUserId: "demo-usr-producao",
    sectorId: "sec-arte-final",
    machineId: null,
    startedAt: null,
    metadata: { dobra: "central" },
  },
  {
    id: "demo-itm-3002-banner",
    orderId: "demo-ord-3002",
    productId: "demo-prd-banner-lona",
    description: "Banner Lona 440g com Bastao",
    quantity: 8,
    unitPrice: 99.9,
    discount: 0,
    total: 799.2,
    status: "PICKING",
    position: 0,
    priority: "URGENT",
    dueDate: iso(2),
    assignedUserId: "demo-usr-producao",
    sectorId: "sec-acabamento",
    machineId: "demo-maq-guilhotina",
    startedAt: null,
    metadata: { evento: "Feira local" },
  },
  {
    id: "demo-itm-3003-cardapio",
    orderId: "demo-ord-3003",
    productId: "demo-prd-cardapio-laminado",
    description: "Cardapio Laminado A3",
    quantity: 40,
    unitPrice: 24.9,
    discount: 50,
    total: 946,
    status: "PENDING",
    position: 0,
    priority: "NORMAL",
    dueDate: iso(8),
    assignedUserId: "demo-usr-producao",
    sectorId: "sec-acabamento",
    machineId: null,
    startedAt: null,
    metadata: { acabamento: "laminacao fosca" },
  },
];

const quoteItems = [
  {
    id: "demo-qit-2001-caixa",
    quoteId: "demo-quo-2001",
    productId: "demo-prd-caixa-kraft",
    description: "Caixa Kraft Personalizada 18x18x10",
    quantity: 300,
    unitPrice: 12.9,
    discount: 120,
    total: 3750,
    notes: "Impressao em uma cor.",
  },
  {
    id: "demo-qit-2001-adesivo",
    quoteId: "demo-quo-2001",
    productId: "demo-prd-adesivo-vinil",
    description: "Adesivo Vinil Redondo 5cm",
    quantity: 500,
    unitPrice: 0.28,
    discount: 0,
    total: 140,
    notes: "Aplicacao em embalagem.",
  },
  {
    id: "demo-qit-2002-folder",
    quoteId: "demo-quo-2002",
    productId: "demo-prd-folder-promocional",
    description: "Folder Promocional A4 150g",
    quantity: 1000,
    unitPrice: 0.36,
    discount: 0,
    total: 360,
    notes: "Campanha promocional.",
  },
];

async function main() {
  const createdAt = iso(0);
  const updatedAt = iso(0);

  const tenants = [
    {
      id: tenantId,
      name: "Grafica Exemplo",
      slug: tenantId,
      status: "ACTIVE",
      metadata: { seededBy: "seed-demo-data" },
      createdAt,
      updatedAt,
    },
  ];

  const sectors = [
    ["sec-comercial", "Comercial", "Atendimento, negociacao e orcamentos.", "#6d4aff", "users", 0, 65, "98%", "2h"],
    ["sec-arte-final", "Arte Final", "Fechamento de arquivo e prova digital.", "#0099ff", "palette", 1, 70, "96%", "4h"],
    ["sec-impressao", "Impressao", "Impressao digital e grandes formatos.", "#00b870", "printer", 2, 82, "95%", "8h"],
    ["sec-acabamento", "Acabamento", "Corte, laminacao, montagem e conferencia.", "#ff8a00", "scissors", 3, 58, "97%", "6h"],
    ["demo-sec-expedicao", "Expedicao", "Separacao, embalagem e despacho.", "#db2777", "truck", 4, 45, "99%", "3h"],
  ].map(([id, name, description, color, icon, kanbanOrder, capacity, sla, lead]) => ({
    id,
    tenantId,
    name,
    description,
    color,
    icon,
    status: "OPERATIONAL",
    kanbanOrder,
    capacity,
    sla,
    lead,
    metadata: { seededBy: "seed-demo-data" },
    createdAt,
    updatedAt,
  }));

  const users = [
    {
      id: "demo-usr-admin",
      type: "ADMIN",
      name: "Marina Costa",
      email: "marina.admin@graphflow.demo",
      phone: "(11) 90000-1000",
      document: "12345678901",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80",
      role: "ADMIN",
      permissions: ["*"],
      status: "ACTIVE",
      metadata: { department: "Diretoria", jobTitle: "Administradora" },
    },
    {
      id: "demo-usr-comercial",
      type: "OPERATOR",
      name: "Lucas Almeida",
      email: "lucas.comercial@graphflow.demo",
      phone: "(11) 90000-1001",
      document: "22345678901",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80",
      role: "MANAGER",
      permissions: [
        "dashboard:read",
        "clients:read",
        "clients:write",
        "quotes:read",
        "quotes:write",
        "orders:read",
        "suppliers:read",
        "purchases:read",
      ],
      status: "ACTIVE",
      metadata: { department: "Comercial", jobTitle: "Gerente comercial" },
    },
    {
      id: "demo-usr-producao",
      type: "OPERATOR",
      name: "Bianca Rocha",
      email: "bianca.producao@graphflow.demo",
      phone: "(11) 90000-1002",
      document: "32345678901",
      avatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=256&q=80",
      role: "OPERATOR",
      permissions: [
        "dashboard:read",
        "orders:read",
        "production:read",
        "production:write",
        "machines:read",
        "inventory:read",
        "inventory:write",
        "fiscal:read",
      ],
      status: "ACTIVE",
      metadata: { department: "Producao", jobTitle: "Coordenadora de producao" },
    },
    {
      id: "demo-usr-financeiro",
      type: "OPERATOR",
      name: "Renato Lima",
      email: "renato.financeiro@graphflow.demo",
      phone: "(11) 90000-1003",
      document: "42345678901",
      avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=256&q=80",
      role: "FINANCE",
      permissions: [
        "dashboard:read",
        "finance:read",
        "finance:write",
        "payments:read",
        "payments:write",
        "suppliers:read",
        "suppliers:write",
        "purchases:read",
        "purchases:write",
        "fiscal:read",
        "fiscal:write",
        "audit:read",
        "reports:read",
        "orders:read",
        "quotes:read",
      ],
      status: "ACTIVE",
      metadata: { department: "Financeiro", jobTitle: "Analista financeiro" },
    },
  ].map((user) => ({
    ...user,
    tenantId,
    createdAt,
    updatedAt,
  }));

  const customers = [
    {
      id: "demo-cus-agencia-viva",
      personType: "PJ",
      documentType: "CNPJ",
      document: "10203040000155",
      name: "Agencia Viva",
      companyName: "Agencia Viva Comunicacao Ltda",
      email: "compras@agenciaviva.demo",
      phone: "(11) 3111-1200",
      whatsapp: "(11) 98888-1200",
      addressCity: "Sao Paulo",
      addressState: "SP",
      notes: "Cliente recorrente de materiais promocionais.",
      status: "ACTIVE",
      metadata: { segmento: "marketing" },
    },
    {
      id: "demo-cus-cafe-das-ruas",
      personType: "PJ",
      documentType: "CNPJ",
      document: "20304050000166",
      name: "Cafe das Ruas",
      companyName: "Cafe das Ruas Alimentos Ltda",
      email: "operacoes@cafedasruas.demo",
      phone: "(21) 3222-2200",
      whatsapp: "(21) 97777-2200",
      addressCity: "Rio de Janeiro",
      addressState: "RJ",
      notes: "Cardapios, embalagens e adesivos para lojas.",
      status: "ACTIVE",
      metadata: { segmento: "alimentacao" },
    },
    {
      id: "demo-cus-eventos-luna",
      personType: "PJ",
      documentType: "CNPJ",
      document: "30405060000177",
      name: "Eventos Luna",
      companyName: "Eventos Luna Producoes Ltda",
      email: "producao@eventosluna.demo",
      phone: "(31) 3333-3300",
      whatsapp: "(31) 96666-3300",
      addressCity: "Belo Horizonte",
      addressState: "MG",
      notes: "Alta demanda de banners e sinalizacao.",
      status: "ATTENTION",
      metadata: { segmento: "eventos" },
    },
    {
      id: "demo-cus-floratta",
      personType: "PJ",
      documentType: "CNPJ",
      document: "40506070000188",
      name: "Floratta Presentes",
      companyName: "Floratta Presentes e Decoracao Ltda",
      email: "contato@floratta.demo",
      phone: "(41) 3444-4400",
      whatsapp: "(41) 95555-4400",
      addressCity: "Curitiba",
      addressState: "PR",
      notes: "Kits personalizados e embalagens premium.",
      status: "ACTIVE",
      metadata: { segmento: "varejo" },
    },
  ].map((customer) => ({
    ...customer,
    tenantId,
    avatarUrl: "",
    addressZip: "",
    addressStreet: "",
    addressNumber: "",
    addressComplement: "",
    addressDistrict: "",
    addressCountry: "BR",
    createdAt,
    updatedAt,
  }));

  const productRows = products.map((product) => ({
    ...product,
    tenantId,
    createdAt,
    updatedAt,
    deletedAt: null,
  }));

  const inventories = products.map((product) => ({
    id: `demo-inv-${product.id.replace("demo-prd-", "")}`,
    tenantId,
    productId: product.id,
    name: product.name,
    category: product.category,
    quantity: product.stockQty,
    reservedQuantity: Math.round(Number(product.stockMin) * 0.2),
    availableQuantity: Number(product.stockQty) - Math.round(Number(product.stockMin) * 0.2),
    minQuantity: product.stockMin,
    unit: product.unitType,
    imageUrl: product.thumbnailUrl,
    lastMove: "seed demo",
    metadata: { seededBy: "seed-demo-data" },
    createdAt,
    updatedAt,
  }));

  const machines = [
    {
      id: "demo-maq-indigo",
      sectorId: "sec-impressao",
      name: "HP Indigo 7900",
      model: "Indigo 7900",
      serialNumber: "HP-DEMO-7900",
      status: "OPERATIONAL",
      capacityPerHour: 480,
      nextMaintenanceAt: iso(18),
      lastMaintenanceAt: iso(-35),
      totalUsageMinutes: 18400,
      costMonth: 18600,
      description: "Impressora digital principal para pequenas e medias tiragens.",
      metadata: { fabricante: "HP" },
    },
    {
      id: "demo-maq-uv",
      sectorId: "sec-impressao",
      name: "Roland UV VersaUV",
      model: "VersaUV LEC2",
      serialNumber: "RL-DEMO-UV",
      status: "MAINTENANCE",
      capacityPerHour: 95,
      nextMaintenanceAt: iso(3),
      lastMaintenanceAt: iso(-60),
      totalUsageMinutes: 8200,
      costMonth: 9400,
      description: "Equipamento UV para adesivos e materiais rigidos.",
      metadata: { fabricante: "Roland" },
    },
    {
      id: "demo-maq-guilhotina",
      sectorId: "sec-acabamento",
      name: "Guilhotina Polar 92",
      model: "Polar 92",
      serialNumber: "PL-DEMO-92",
      status: "OPERATIONAL",
      capacityPerHour: 900,
      nextMaintenanceAt: iso(24),
      lastMaintenanceAt: iso(-18),
      totalUsageMinutes: 7200,
      costMonth: 5200,
      description: "Corte e refilo de papelaria.",
      metadata: { fabricante: "Polar" },
    },
  ].map((machine) => ({
    ...machine,
    tenantId,
    createdAt,
    updatedAt,
  }));

  const orders = [
    {
      id: "demo-ord-3001",
      customerId: "demo-cus-agencia-viva",
      userId: "demo-usr-comercial",
      number: "PED-3001",
      status: "IN_PRODUCTION",
      paymentStatus: "PARTIAL",
      productionStatus: "IN_PROGRESS",
      subtotal: 410,
      discountAmount: 0,
      taxAmount: 0,
      shippingAmount: 0,
      total: 410,
      paidAmount: 205,
      remainingAmount: 205,
      notes: "Campanha institucional com prazo curto.",
      internalNotes: "Prioridade comercial.",
      expectedDeliveryAt: iso(5),
      metadata: { canal: "WhatsApp" },
      createdAt: iso(-2),
    },
    {
      id: "demo-ord-3002",
      customerId: "demo-cus-eventos-luna",
      userId: "demo-usr-comercial",
      number: "PED-3002",
      status: "CONFIRMED",
      paymentStatus: "PENDING",
      productionStatus: "IN_QUEUE",
      subtotal: 799.2,
      discountAmount: 0,
      taxAmount: 0,
      shippingAmount: 0,
      total: 799.2,
      paidAmount: 0,
      remainingAmount: 799.2,
      notes: "Banners para feira local.",
      internalNotes: "Validar ilhos com cliente.",
      expectedDeliveryAt: iso(2),
      metadata: { canal: "Portal" },
      createdAt: iso(-1),
    },
    {
      id: "demo-ord-3003",
      customerId: "demo-cus-cafe-das-ruas",
      userId: "demo-usr-comercial",
      number: "PED-3003",
      status: "CONFIRMED",
      paymentStatus: "PENDING",
      productionStatus: "WAITING",
      subtotal: 946,
      discountAmount: 50,
      taxAmount: 0,
      shippingAmount: 0,
      total: 946,
      paidAmount: 0,
      remainingAmount: 946,
      notes: "Cardapios novos para filial Botafogo.",
      internalNotes: "Aguardar fotos finais do cliente.",
      expectedDeliveryAt: iso(8),
      metadata: { canal: "Email" },
      createdAt: iso(0),
    },
  ].map((order) => ({
    ...order,
    tenantId,
    quoteId: null,
    carrier: null,
    trackingCode: null,
    updatedAt,
    deletedAt: null,
  }));

  const orderRows = orderItems.map((item) => ({
    ...item,
    tenantId,
    variantId: null,
    finishedAt: null,
    pausedAt: null,
    createdAt,
    updatedAt,
  }));

  const quotes = [
    {
      id: "demo-quo-2001",
      customerId: "demo-cus-floratta",
      userId: "demo-usr-comercial",
      number: "ORC-2001",
      status: "SENT",
      validUntil: iso(12),
      notes: "Validade de 12 dias. Frete a combinar.",
      internalNotes: "Cliente quer embalagem premium para Dia dos Namorados.",
      subtotal: 3890,
      discountAmount: 120,
      taxAmount: 0,
      total: 3890,
      metadata: { origem: "briefing comercial" },
      createdAt: iso(-1),
    },
    {
      id: "demo-quo-2002",
      customerId: "demo-cus-agencia-viva",
      userId: "demo-usr-comercial",
      number: "ORC-2002",
      status: "DRAFT",
      validUntil: iso(15),
      notes: "Rascunho para campanha de varejo.",
      internalNotes: "Revisar margem antes de enviar.",
      subtotal: 360,
      discountAmount: 0,
      taxAmount: 0,
      total: 360,
      metadata: { origem: "telefone" },
      createdAt: iso(0),
    },
  ].map((quote) => ({
    ...quote,
    tenantId,
    updatedAt,
    deletedAt: null,
  }));

  const quoteRows = quoteItems.map((item) => ({
    ...item,
    tenantId,
    variantId: null,
    createdAt,
    updatedAt,
  }));

  const finance = [
    ["demo-fin-receber-3001", "demo-ord-3001", null, "Entrada PED-3001", "receivable", 205, "Hoje", "Recebido"],
    ["demo-fin-saldo-3001", "demo-ord-3001", null, "Saldo PED-3001", "receivable", 205, "5 dias", "Pendente"],
    ["demo-fin-receber-3002", "demo-ord-3002", null, "Pedido PED-3002", "receivable", 799.2, "2 dias", "Pendente"],
    ["demo-fin-pagar-papel", null, null, "Compra papel couchê", "payable", 5400, "15/06/2026", "Pendente"],
    ["demo-fin-caixa", null, null, "Fluxo de caixa diario", "cash", 3260, "Hoje", "Projetado"],
  ].map(([id, orderId, quoteId, label, type, value, due, status]) => ({
    id,
    tenantId,
    orderId,
    quoteId,
    label,
    type,
    value: money(Number(value)),
    due,
    status,
    metadata: { seededBy: "seed-demo-data" },
    createdAt,
    updatedAt,
  }));

  const files = [
    ["demo-fil-briefing-viva", "Briefing Agencia Viva.pdf", "PDF", "1.2 MB", "PED-3001", "https://example.com/demo/briefing-agencia-viva.pdf"],
    ["demo-fil-arte-banner", "Arte final banners Luna.ai", "AI", "18 MB", "PED-3002", "https://example.com/demo/arte-banners-luna.ai"],
    ["demo-fil-cardapio", "Fotos cardapio Cafe das Ruas.zip", "ZIP", "42 MB", "PED-3003", "https://example.com/demo/fotos-cardapio.zip"],
  ].map(([id, name, type, size, linkedTo, url]) => ({
    id,
    tenantId,
    name,
    type,
    size,
    linkedTo,
    url,
    metadata: { seededBy: "seed-demo-data" },
    createdAt,
    updatedAt,
  }));

  const notifications = [
    ["demo-not-ordem-urgente", "Pedido urgente", "PED-3002 precisa entrar em producao hoje.", "warning", false],
    ["demo-not-manutencao-uv", "Manutencao aberta", "Roland UV VersaUV esta em manutencao preventiva.", "danger", false],
    ["demo-not-orcamento", "Orcamento enviado", "ORC-2001 foi enviado para Floratta Presentes.", "success", true],
    ["demo-not-estoque", "Estoque em atencao", "Banner Lona 440g esta proximo do minimo configurado.", "info", false],
  ].map(([id, title, message, tone, read]) => ({
    id,
    tenantId,
    title,
    message,
    tone,
    read,
    metadata: { seededBy: "seed-demo-data" },
    createdAt,
  }));

  const usageLogs = [
    {
      id: "demo-use-indigo-3001",
      tenantId,
      machineId: "demo-maq-indigo",
      userId: "demo-usr-producao",
      orderItemId: "demo-itm-3001-cartao",
      startTime: iso(-1),
      endTime: null,
      duration: null,
      notes: "Cartoes premium em producao.",
      createdAt: iso(-1),
    },
  ];

  const maintenanceTickets = [
    {
      id: "demo-mnt-uv-001",
      tenantId,
      machineId: "demo-maq-uv",
      openedByUserId: "demo-usr-producao",
      assignedUserId: "demo-usr-producao",
      priority: "HIGH",
      status: "OPEN",
      title: "Revisar cabeca UV",
      description: "Falhas intermitentes de cura em materiais rigidos.",
      openedAt: iso(0),
      closedAt: null,
      metadata: { seededBy: "seed-demo-data" },
      createdAt,
      updatedAt,
    },
  ];

  const permissions = [
    ["demo-usp-lucas-comercial", "demo-usr-comercial", "sec-comercial", true],
    ["demo-usp-bianca-arte", "demo-usr-producao", "sec-arte-final", true],
    ["demo-usp-bianca-impressao", "demo-usr-producao", "sec-impressao", true],
    ["demo-usp-bianca-acabamento", "demo-usr-producao", "sec-acabamento", true],
    ["demo-usp-renato-comercial", "demo-usr-financeiro", "sec-comercial", false],
  ].map(([id, userId, sectorId, canWrite]) => ({
    id,
    tenantId,
    userId,
    sectorId,
    canRead: true,
    canWrite,
    createdAt,
    updatedAt,
  }));

  const summary = {
    tenants: await upsertRows("tenants", tenants, "seed tenants"),
    sectors: await upsertRows("sectors", sectors, "seed sectors"),
    users: await upsertRows("users", users, "seed users"),
    userSectorPermissions: await upsertRows("user_sector_permissions", permissions, "seed user sector permissions"),
    customers: await upsertRows("customers", customers, "seed customers"),
    products: await upsertRows("products", productRows, "seed products"),
    inventory: await upsertRows("inventories", inventories, "seed inventory"),
    machines: await upsertRows("machines", machines, "seed machines"),
    orders: await upsertRows("orders", orders, "seed orders"),
    orderItems: await upsertRows("order_items", orderRows, "seed order items"),
    machineUsage: await upsertRows("machine_usage_logs", usageLogs, "seed machine usage logs"),
    maintenanceTickets: await upsertRows("maintenance_tickets", maintenanceTickets, "seed maintenance tickets"),
    quotes: await upsertRows("quotes", quotes, "seed quotes"),
    quoteItems: await upsertRows("quote_items", quoteRows, "seed quote items"),
    finance: await upsertRows("financial_transactions", finance, "seed finance"),
    files: await upsertRows("files", files, "seed files"),
    notifications: await upsertRows("notifications", notifications, "seed notifications"),
  };

  console.log(JSON.stringify({ ok: true, tenantId, summary }, null, 2));
}

await main();
